name-template: v$NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
categories:
  - title: 🚀 New Features
    label: feature
  - title: 📈 Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📝 Documentation
    label: documentation
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES

  ## [Docker image](https://quay.io/repository/signalfx/splunk-otel-collector)
  This release is available as a Docker image:
    
  `quay.io/signalfx/splunk-otel-collector:$NEXT_MINOR_VERSION`
  
